markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Ahmed Fathalla 
url: http://afathalla.com
description: In search of an identity
twitter: afathalla
github: afathalla
gravatar_url: http://www.gravatar.com/avatar/252b5b6b565bb328eba02fff6b7b533f
